### ISSUE TITLE
no matches found: /home/chengjianhua/.antigen-etc/bundle.d/*.zsh

### ISSUE THREAD

**Issue by chengjianhua** [gantsign/ansible_role_antigen#50]
After performing ansible playbook which configures the role like below:
```
    - role: gantsign.antigen
      users:
        - username: "{{ ansible_user }}"
          antigen_libraries:
            - name: oh-my-zsh
```

Then I login into my remote host, I encountered the following errors:
```
/home/chengjianhua/.antigenrc:14: no matches found: /home/chengjianhua/.antigen-etc/bundle.d/*.zsh
```

It seems that the empty bundle list caused glob expression to fail:
https://github.com/gantsign/ansible_role_antigen/blob/2e3f5719e852de66458eeb4f9ec67e2385173303/templates/antigenrc.j2#L12
