### ISSUE TITLE
Apply role on Ubuntu 20.04 (focal) doesn't seem to work completely

### ISSUE THREAD

**Issue by sbancal** [gantsign/ansible_role_antigen#53]
I applied the following playbook on 2 fresh servers :

```yml
- hosts: all
  roles:
    - role: gantsign.antigen
      users:
        - username: root
          antigen_libraries:
            - name: oh-my-zsh
              env:
                DISABLE_AUTO_UPDATE: '"true"'
          antigen_theme:
            name: robbyrussell
          antigen_bundles:
            - name: git
            - name: docker
            - name: docker-compose
            - name: command-not-found
```

When I `ssh root@server`, I get the zsh shell, but the theme and plugins don't seem to work as expected.
On 1 server, the theme is activated, on the other not (!?).
On both, the plugins don't work and the following command returns an empty result.

```bash
echo $plugins
```

Let me know if I can post more infos to help.

BTW, is there a clean/simple way to remove everything related to this role on the servers so I can run it again from scratch ?

Regards
